# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QNotebook
                                 A QGIS plugin
 Jupyter-style notebook for QGIS Python Console
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-09-10
        copyright            : (C) 2025 by Federico Gianoli
        email                : gianoli.federico@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QNotebook class from file QNotebook.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qnotebook import QNotebook
    return QNotebook(iface)
